import theming


class MineTheme(theming.Theme):
    COLOR_INFORMATION_BAR = (-1, 238)
    COLOR_STATUS_XA = (53, -1)
    COLOR_STATUS_AWAY = (214, -1)
    COLOR_STATUS_DND = (160, -1)
    COLOR_STATUS_CHAT = (34, -1)
    COLOR_STATUS_UNAVAILABLE = (242, -1)
    COLOR_STATUS_ONLINE = (27, -1)
    COLOR_STATUS_NONE = (27, -1)

    COLOR_VERTICAL_SEPARATOR = (244, -1)
    COLOR_NEW_TEXT_SEPARATOR = (213, -1)
    COLOR_MORE_INDICATOR = (6, 4)

    COLOR_TAB_NORMAL = (-1, 238)
    COLOR_TAB_NONEMPTY = (-1, 238)
    COLOR_TAB_CURRENT = (-1, 16)
    COLOR_TAB_COMPOSING = (3, 238)
    COLOR_TAB_NEW_MESSAGE = (3, 238)
    COLOR_TAB_HIGHLIGHT = (1, 238)
    COLOR_TAB_ATTENTION = (6, 238)
    COLOR_TAB_PRIVATE = (2, 238)
    COLOR_TAB_DISCONNECTED = (13, 238)
    COLOR_TAB_SCROLLED = (66, 238)

    COLOR_TOPIC_BAR = (-1, 238)
    COLOR_SCROLLABLE_NUMBER = (220, 238, 'b')
    COLOR_SELECTED_ROW = (-1, 238)
    COLOR_PRIVATE_NAME = (173, 238)
    COLOR_CONVERSATION_NAME = (2, 238)
    COLOR_CONVERSATION_RESOURCE = (58, 238)
    COLOR_GROUPCHAT_NAME = (106, 238)
    COLOR_COLUMN_HEADER = (36, 238)

    COLOR_VERTICAL_TAB_NORMAL = (7, -1)
    COLOR_VERTICAL_TAB_CURRENT = (-1, 8)
    COLOR_VERTICAL_TAB_NEW_MESSAGE = (3, -1)
    COLOR_VERTICAL_TAB_COMPOSING = (3, -1)
    COLOR_VERTICAL_TAB_HIGHLIGHT = (1, -1)
    COLOR_VERTICAL_TAB_PRIVATE = (2, -1)
    COLOR_VERTICAL_TAB_ATTENTION = (6, -1)
    COLOR_VERTICAL_TAB_DISCONNECTED = (8, -1)

    COLOR_INFORMATION_TEXT = (244, -1)
    COLOR_LOG_MSG = (244, -1)


theme = MineTheme()
